#!/usr/bin/env bash

set -eu -o pipefail

scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
cd $scriptdir/..

NDK=$1
DEST_CPU_ARCH=$2

if [[ ! -d "$NDK" ]]; then
  echo "Android NDK directory '$NDK' invalid"
  exit 1
fi

ln -fs $NDK ./deps/v8/third_party/android_ndk

# We do not export anything about the tool chain, as v8
# will pick their own toolchain for android from the ndk

cd ./deps/v8

python3 ./tools/node/fetch_deps.py $PWD

gn_args=$(cat <<EOF
target_cpu="$DEST_CPU_ARCH"
v8_target_cpu = "$DEST_CPU_ARCH"
target_os="android"
is_component_build=false
use_debug_fission=false
use_custom_libcxx=false
v8_use_external_startup_data=false
icu_use_data_file=false
EOF
)

echo gn_args $gn_args

echo "executing gn gen"

./buildtools/linux64/gn gen out.gn/android-$DEST_CPU_ARCH "--args=$gn_args"

echo "executing ninja"

ninja -C out.gn/android-$DEST_CPU_ARCH "libmgcv8"
